[workspace]
channels = ["conda-forge"]
name = "env-myst"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-fluidsim = "pip install ../.. -v --config-settings=setup-args=-Dtransonic-backend=python"

[dependencies]
mystmd = ">=1.9.1,<2"
typst = ">=0.14.2,<0.15"
fluiddyn = ">=0.9.0,<0.10"
fluidfft = ">=0.4.5,<0.5"
h5py = ">=3.16.0,<4"
pyfftw = ">=0.15.1,<0.16"
transonic = ">=0.8.0,<0.9"
pip = ">=26.1.1,<27"
h5netcdf = ">=1.8.1,<2"
xarray = ">=2026.4.0,<2027"
rich = ">=15.0.0,<16"
scipy = ">=1.17.1,<2"
matplotlib = ">=3.10.9,<4"
jupyterlab = ">=4.5.7,<5"
jupytext = ">=1.19.3,<2"
