
figures_256_kmaxeta_1.pdf: notebook_individual.md
	PATH_SIMUL_DIR="/data/data_fluidsimexport/isotropic_forcing_alias/ns3d_RK2_phaseshift_random_split_trunc1.000_256x256x256_V2pix2pix2pi_fNone_2026-05-21_15-45-33" myst build --execute --typst notebook_individual.md -o figures_256_kmaxeta_1.pdf

cleanall:
	rm -f *.pdf
