
figures.pdf: notebook_individual.md
	PATH_SIMUL_DIR="/fsnet/project/meige/2026/26KOLMO/from_legi/strat/ns3d.strat_N10_kmax_eta0_640x640x640_V2pix2pix2pi_fNone_N10_2026-06-10_18-25-13" myst build --execute --typst notebook_individual.md -o figures_640_N_10.pdf

cleanall:
	rm -f *.pdf
