
figures_256_kmaxeta_1_N_2.pdf: notebook_individual.md
	PATH_SIMUL_DIR="/data/data_fluidsimexport/kolmo_laws/strat/ns3d.strat_N2_kmax_eta1_256x256x256_V2pix2pix2pi_fNone_N2_2026-05-28_09-08-46" myst build --execute --typst notebook_individual.md -o figures_256_kmaxeta_1_N_2.pdf

cleanall:
	rm -f *.pdf
