#!/bin/bash

PYTHONCOMMAND="$@"

if [ -z "$PYTHONCOMMAND" ];
then
    echo "This script takes at least one argument (the name of the python script)"
    exit 0
fi

if [ -n "$SP_HOSTFILE" ];
then
    source ~/.profile
fi

python -u $PYTHONCOMMAND
